workspace = { members = ["src"] }
[package]
name = "Day-09_Trapping-Rain-Water"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
